<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BBA-AVIATION-MANAGEMENT.pdf</name>
   <tag></tag>
   <elementGuidId>02fd298b-b5ca-4ce1-824e-0e3a6fc2c4ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.linktext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; BBA-AVIATION-MANAGEMENT.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59ae6d93-bb1a-40c7-8c2c-e681589488f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linktext</value>
      <webElementGuid>8a7a4ff3-b4b0-4623-8de7-085f921a07cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>2020-2021/Commerce-and-Management/BBA-AVIATION-MANAGEMENT.pdf</value>
      <webElementGuid>788dde4e-3507-44fa-90bb-619312e79dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BCOM PROFESSIONAL ACCOUNTING </value>
      <webElementGuid>5b641c8b-621a-4f83-9854-f4da13460f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0860dca0-1c5e-4682-b0d5-3ecf9d747f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BBA-AVIATION-MANAGEMENT.pdf</value>
      <webElementGuid>f2947a9d-2800-44ed-82b7-12c08c79ff71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;wrapper row3&quot;]/main[@class=&quot;hoc container clear&quot;]/div[@id=&quot;wrapper&quot;]/div[@class=&quot;content three_quarter&quot;]/a[@class=&quot;linktext&quot;]</value>
      <webElementGuid>b1325481-c50e-45c1-aa92-7c515c260b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/a</value>
      <webElementGuid>54baec88-9fb1-4c63-b009-96a320aac666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BBA-AVIATION-MANAGEMENT.pdf')]</value>
      <webElementGuid>2e21ee29-abcc-440f-908a-f734c0d0ce34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='நான் முதல்வன்'])[1]/following::a[1]</value>
      <webElementGuid>183b68f9-6cae-47f8-a4b8-8eed38ea08a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '2020-2021/Commerce-and-Management/BBA-AVIATION-MANAGEMENT.pdf')]</value>
      <webElementGuid>9a48c6b0-a046-4bd5-b073-03d1248b6fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>7594d1c6-5999-4172-acdb-0617f9f018f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '2020-2021/Commerce-and-Management/BBA-AVIATION-MANAGEMENT.pdf' and @title = 'BCOM PROFESSIONAL ACCOUNTING ' and (text() = ' BBA-AVIATION-MANAGEMENT.pdf' or . = ' BBA-AVIATION-MANAGEMENT.pdf')]</value>
      <webElementGuid>311f4332-9119-4f59-8cff-22778e855cbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
