<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BCOM-PROFESSIONAL-ACCOUNTING.pdf</name>
   <tag></tag>
   <elementGuidId>60eba2af-adc8-4d22-b8c9-7e2fa7ef1e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/a[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; BCOM-PROFESSIONAL-ACCOUNTING.pdf&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df069a1b-4111-469f-b122-cc4ab709ca5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linktext</value>
      <webElementGuid>9f884859-1b39-409e-a375-4198f6425b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>2020-2021/Commerce-and-Management/BCOM-PROFESSIONAL-ACCOUNTING.pdf</value>
      <webElementGuid>b369569d-e758-415f-a22e-bdf9772b6a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BCOM PROFESSIONAL ACCOUNTING </value>
      <webElementGuid>ce38d610-4c01-4d11-9747-45b3e0272810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f792bc5d-4442-4e98-82e9-23443ca24012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BCOM-PROFESSIONAL-ACCOUNTING.pdf</value>
      <webElementGuid>dae71316-aff9-440b-91fc-c0fe4e956d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;wrapper row3&quot;]/main[@class=&quot;hoc container clear&quot;]/div[@id=&quot;wrapper&quot;]/div[@class=&quot;content three_quarter&quot;]/a[@class=&quot;linktext&quot;]</value>
      <webElementGuid>5c9885df-56e4-46a4-a018-6c1b6a91f763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/a[8]</value>
      <webElementGuid>adcedb76-5807-45bc-af92-96b69dd9ccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BCOM-PROFESSIONAL-ACCOUNTING.pdf')]</value>
      <webElementGuid>fbdab6b6-89fd-48dd-8efd-bb0b29449786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '2020-2021/Commerce-and-Management/BCOM-PROFESSIONAL-ACCOUNTING.pdf')]</value>
      <webElementGuid>61af4c9a-1404-4598-a261-396e696f2ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[8]</value>
      <webElementGuid>088e5a72-08e3-4c15-8934-6a3adf01e926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '2020-2021/Commerce-and-Management/BCOM-PROFESSIONAL-ACCOUNTING.pdf' and @title = 'BCOM PROFESSIONAL ACCOUNTING ' and (text() = ' BCOM-PROFESSIONAL-ACCOUNTING.pdf' or . = ' BCOM-PROFESSIONAL-ACCOUNTING.pdf')]</value>
      <webElementGuid>1415fba8-2a83-4e29-9931-58b5f25edecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
