<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_jegankumarbdu.ac.in</name>
   <tag></tag>
   <elementGuidId>64e0941f-5d44-4047-acf2-d619cb9d514f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;jegankumar@bdu.ac.in&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6dff9bec-e1b8-4dc1-8970-4a65a7b3cc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:jegankumar@bdu.ac.in</value>
      <webElementGuid>f1ef6f90-f96d-4a47-8d54-0947f83dcd86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jegankumar@bdu.ac.in</value>
      <webElementGuid>d7d5091f-02ba-48ab-be16-87275663d06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[1]/td[5]/a[1]</value>
      <webElementGuid>f09c20ad-8274-445a-ad18-c91f8ea0c26f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr/td[5]/a</value>
      <webElementGuid>f61336ea-d71c-4817-a36d-1717c383d2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'jegankumar@bdu.ac.in')]</value>
      <webElementGuid>7118b0f3-004e-4232-bbe0-127881b9b9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. R. Jegankumar'])[1]/following::a[1]</value>
      <webElementGuid>8e07fa1e-53a8-486c-8e84-13da3ecb78e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia University Ranking'])[1]/preceding::a[1]</value>
      <webElementGuid>e85bfacf-a298-4147-a295-501df23e9f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr. C. Prahalathan'])[1]/preceding::a[1]</value>
      <webElementGuid>ef734b75-618f-4906-a1bb-4047a4d06b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jegankumar@bdu.ac.in']/parent::*</value>
      <webElementGuid>8c1aca1f-257c-4b97-a4f7-c76b63ec3784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:jegankumar@bdu.ac.in')]</value>
      <webElementGuid>15e9c9d9-36e6-4d37-af7e-8b3c1aad57eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>5ed8a7cb-214b-4754-b983-389c3cb653c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:jegankumar@bdu.ac.in' and (text() = 'jegankumar@bdu.ac.in' or . = 'jegankumar@bdu.ac.in')]</value>
      <webElementGuid>73c3bfd9-08ee-4ac6-aa37-7f81edb28fdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
