<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unfilled Feedback Forms</name>
   <tag></tag>
   <elementGuidId>4cd145b0-2cec-4ddc-b84c-8a91b3da9799</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.span1 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='team']/div/div[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Unfilled Feedback Forms&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14c2b17d-c0c4-4605-ae45-3ce2fd2674ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../assets/docs/iqac/feedback/1.4.1-Unfilled-Feedback-Forms.pdf</value>
      <webElementGuid>8fd2726c-3f85-4b1d-8c83-4f7bb7834682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>23aa9c5d-4929-47aa-9566-547f3192f10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unfilled Feedback Forms </value>
      <webElementGuid>6b6f8702-6512-47a0-8732-6fa122c90b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;team&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;member&quot;]/div[@class=&quot;member-info&quot;]/div[@class=&quot;span1&quot;]/a[1]</value>
      <webElementGuid>0cb41971-2a2f-4332-9518-a255642f7d7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='team']/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>51092dbb-08ba-4c40-92ff-c7187159afdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Unfilled Feedback Forms')]</value>
      <webElementGuid>d3cfe8e9-d91b-402a-b8e3-91d0a466f79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A. Feedback Forms'])[1]/following::a[1]</value>
      <webElementGuid>ffe0e163-43f5-4bb9-ab01-a60a50180154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B. Filled Forms (Sample)'])[1]/preceding::a[1]</value>
      <webElementGuid>ac8df52a-ff95-4505-bf65-250f0d9ae152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C. Feedback Analysis Report'])[1]/preceding::a[3]</value>
      <webElementGuid>c21b0541-ac47-4807-a9de-33dfb4fe3c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../assets/docs/iqac/feedback/1.4.1-Unfilled-Feedback-Forms.pdf')]</value>
      <webElementGuid>f1a109ba-27ee-4821-9a54-620d20d848a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>f0bc481b-e956-4a34-8b0c-ed9c79911cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../assets/docs/iqac/feedback/1.4.1-Unfilled-Feedback-Forms.pdf' and (text() = ' Unfilled Feedback Forms ' or . = ' Unfilled Feedback Forms ')]</value>
      <webElementGuid>c5382724-d83c-4545-b7e2-04d09250edfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
