<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Visit Site</name>
   <tag></tag>
   <elementGuidId>0f2a944c-d97d-4d7a-a03c-befcea86b54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.locate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.locate >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>941fa5b3-d7f9-4a53-83ff-b5a3386b016b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>national-institute-education.php</value>
      <webElementGuid>aa9d22f7-8814-4f6d-8efc-0531b38cbb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>locate</value>
      <webElementGuid>ac8c3419-3bbd-45e9-a479-7b3b5d105a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>870e48e1-1263-4457-8663-b68048415624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visit Site  </value>
      <webElementGuid>bb9d3ab3-92b5-4fed-b05b-b48f3e93a997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;inner-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-3&quot;]/div[@class=&quot;region-box-nie&quot;]/div[@class=&quot;region-box-bg&quot;]/a[@class=&quot;locate&quot;]</value>
      <webElementGuid>67b0180a-701a-4f8f-b92a-771de0c1d5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/div/a</value>
      <webElementGuid>9f5b90de-55b3-4b8b-a9b9-568f092d2380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Visit Site')]</value>
      <webElementGuid>c0e76ae9-eb34-435d-aa7c-bdea5d07ecbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIE'])[1]/following::a[1]</value>
      <webElementGuid>e498699e-5028-4ded-8457-10eda2c85e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCERT Constituents'])[1]/following::a[1]</value>
      <webElementGuid>07007780-bc3f-40e8-8d50-787989cae6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIET'])[1]/preceding::a[2]</value>
      <webElementGuid>4cff7171-33e8-47c0-8bbd-c51dcde952c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'national-institute-education.php')])[2]</value>
      <webElementGuid>98141184-066b-4af7-9829-00438fd9bd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>bcb072c0-c3c1-44a8-81e5-f0b078161472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'national-institute-education.php' and (text() = 'Visit Site  ' or . = 'Visit Site  ')]</value>
      <webElementGuid>509ac71a-97f2-4d0e-8047-e4cc71c2db36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
