<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--Select APPLICATION COST (AS SELECTED_2510b5</name>
   <tag></tag>
   <elementGuidId>bc664b7d-b352-400d-8aba-01d5d7d62f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-outref16-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-outref16-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;--Select APPLICATION COST (AS SELECTED ABOVE)--&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>592b1b60-0dbb-4fa9-86ed-c02d44095dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4978254a-8bb9-49aa-bfc2-ee3db2f4945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-outref16-container</value>
      <webElementGuid>9b0fb076-3569-4d50-bd5d-6177a36efc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>f1b151e5-ceec-449e-81e4-3b057901d21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b9afeb2-add9-428c-9e8e-156aab53da56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select APPLICATION COST (AS SELECTED ABOVE)--</value>
      <webElementGuid>fd685fa2-b98c-4d05-ab30-05479a045862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select APPLICATION COST (AS SELECTED ABOVE)--</value>
      <webElementGuid>2c6603d8-b9a6-47c7-9f6b-885b277ebf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-outref16-container&quot;)</value>
      <webElementGuid>bc216f1d-2888-4de6-9418-927f81459044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-outref16-container']</value>
      <webElementGuid>b746ab34-2486-44ee-8cac-363605c7127c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLICATION COST (AS SELECTED ABOVE) *'])[1]/following::span[5]</value>
      <webElementGuid>a0fa1b5b-0ae1-4057-a30d-e6f0d6625f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT NUMBER'])[1]/following::span[5]</value>
      <webElementGuid>995d68c2-82b6-4b7f-b6af-3e4d446adac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks :'])[1]/preceding::span[3]</value>
      <webElementGuid>9c2df8fa-51d1-417c-8594-684d1b66f9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[1]/preceding::span[3]</value>
      <webElementGuid>2b3893d3-0876-4449-b103-92a9fdabbb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/span/span/span/span/span</value>
      <webElementGuid>06630435-c5b3-4ae7-8c6a-94407206bc33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-outref16-container' and @title = '--Select APPLICATION COST (AS SELECTED ABOVE)--' and (text() = '--Select APPLICATION COST (AS SELECTED ABOVE)--' or . = '--Select APPLICATION COST (AS SELECTED ABOVE)--')]</value>
      <webElementGuid>b6ea09b5-6c6c-4d41-b25d-4e45f7ca9bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
