<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_--Select SEMESTER--</name>
   <tag></tag>
   <elementGuidId>42794c18-e3b3-4152-b4f3-d5a1913ab5f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-outref19-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-outref19-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;--Select SEMESTER--&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d11a9fae-783b-4c4d-9bcd-ab6400bbb2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ba0a230b-801b-4893-8bb0-1724e3d30420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-outref19-container</value>
      <webElementGuid>7a785bb6-dd54-4114-ad2a-27986ebcca33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4c87758a-b546-4c66-8f93-0ddddee37b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b5b3d41e-007c-4e14-8440-735d3fa7e480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>--Select SEMESTER--</value>
      <webElementGuid>140663d1-1174-4225-86fc-5c20d16e71c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select SEMESTER--</value>
      <webElementGuid>305701b9-3879-4f76-b477-7a4e77258e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-outref19-container&quot;)</value>
      <webElementGuid>65735d9e-4ea2-43c8-a667-8925eb2d5916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-outref19-container']</value>
      <webElementGuid>1d9c9fcb-b6d7-4b03-b89b-1ca2f752ac7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEMESTER *'])[1]/following::span[5]</value>
      <webElementGuid>9d078c06-ee0f-496f-ac14-fb499a41f949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACADEMIC YEAR (eg.2014-15) *'])[1]/following::span[5]</value>
      <webElementGuid>acf5a9ac-d62c-42e5-aecd-00a97a1dd29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEGREE *'])[1]/preceding::span[3]</value>
      <webElementGuid>c7072c92-7236-4810-bdd5-b88c56649039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select DEGREE--'])[2]/preceding::span[3]</value>
      <webElementGuid>774aeb7d-56ff-44a1-898a-f5b951c20346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span</value>
      <webElementGuid>5cf5cd3a-42f4-419a-bddd-d25ba1056693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-outref19-container' and @title = '--Select SEMESTER--' and (text() = '--Select SEMESTER--' or . = '--Select SEMESTER--')]</value>
      <webElementGuid>7968c857-62c5-44d2-8724-d4ec5fd022aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
